#!/usr/bin/env bash
#info of school
FILE="school"
if [ -e "$FILE" ]
  then
    echo "school file exists"
      if [ -s "$File" ]
  then
    echo "school file is empty"
   else
      echo "school file is not empty"
  fi
       if [ -f "$File" ] 
   then 
       echo "school file is a regular file"
    fi
      else 
         echo "school file does not exist"
    fi
